package:
  name: gdio
  version: 0.1.8.9

source:
  path: ../gdio


requirements:
  build:
    - python
    - numpy >=1.20*
    - netCDF4
    - python-eccodes
    - eccodes >=2.12.0
    - pyproj

  run:
    - python
    - numpy
    - netCDF4
    - python-eccodes
    - eccodes
    - pyproj

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
