package:
  name: gdio
  version: 0.0.3
source:
  git_rev: master
  git_url: https://github.com/rodri90y/gdio.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - netCDF4
    - pygrib
    - texttable

  run:
    - python
    - numpy
    - netCDF4
    - pygrib
    - texttable

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
