package:
  name: gdio
  version: 0.2.0

source:
  git_url: https://github.com/rodri90y/gdio.git


requirements:
  build:
    - python>=3.7.9
    - numpy>=1.21.5
    - netCDF4>=1.5.8
    - python-eccodes>=1.4.0
    - eccodes>=2.24.2
    - pyproj

  run:
    - python>=3.7.9
    - numpy>=1.21.5
    - netCDF4>=1.5.8
    - python-eccodes>=1.4.0
    - eccodes>=2.24.2
    - pyproj

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
