package:
  name: gdio
  version: 0.1.8.6

source:
  path: ../gdio

requirements:
  build:
    - python
    - setuptools
    - numpy
    - netCDF4
    - python-eccodes
    - eccodes
    - pyproj

  run:
    - python
    - numpy
    - netCDF4
    - python-eccodes
    - eccodes
    - pyproj

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
