package:
  name: gdio
  version: 0.0.2

source:
  git_rev: master
  git_url: https://github.com/rodri90y/gdio.git

requirements:
  build:
    - python
    - setuptools
    - numpy==1.18.4
    - netCDF4==1.5.1.2
    - pygrib==2.0.4
    - texttable==1.6.2

  run:
    - python
    - numpy==1.18.4
    - netCDF4==1.5.1.2
    - pygrib==2.0.4
    - texttable==1.6.2

test:
  imports:
    - gdio

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
