package:
  name: gdio
  version: 0.3.6

source:
  path: .

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  preserve_egg_dir: True

requirements:
  build:
    - {{ compiler('c') }}      # Necessário se houver extensões C
  host:
    - python >=3.9
    - pip
    - setuptools
    - hdf5 >=1.12              # Fixa a versão para evitar o erro de símbolo
    - netcdf4 >=1.5.8
    - h5py >=3.6.0
    - eccodes >=2.25.0
  run:
    - python >=3.9
    - hdf5                     # Garante que a lib de sistema seja instalada
    - netcdf4 >=1.5.8
    - h5py >=3.6.0
    - eccodes >=2.25.0
    - pyproj
    - python-eccodes
    - scipy

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  summary: gridded data io library
