package:
  name: gdio
  version: 0.3.6

source:
  path: ../gdio

build:
    preserve_egg_dir: True

requirements:
  build:
    - python>=3.9.0
    - eccodes>=2.25.0
    - netCDF4>=1.5.8
    - h5py>=3.6.0
    - pyproj
    - python-eccodes
    - scipy

  run:
    - python=3.9.0
    - eccodes>=2.25.0
    - netCDF4>=1.5.8
    - h5py>=3.6.0
    - pyproj
    - python-eccodes
    - scipy

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
