package:
  name: gdio
  version: 0.3.8

source:
  path: .

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - python                   # Removido o >=3.9 para ativar a matriz do conda-build!
    - pip
    - setuptools
    - hdf5
    - netcdf4
    - h5py
    - eccodes

  run:
    - python                   # Deixe apenas "python" aqui! O conda-build injeta o vínculo correto
    - hdf5
    - netcdf4 >=1.5.8
    - h5py >=3.6.0
    - eccodes >=2.25.0
    - pyproj
    - python-eccodes
    - scipy

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  summary: gridded data io library