package:
  name: gdio
  version: 0.2.7

source:
  path: ../gdio

requirements:
  build:
    - python
    - eccodes>=2.25.0
    - netCDF4>=1.5.8
    - pyproj
    - python-eccodes

  run:
    - python
    - eccodes>=2.25.0
    - netCDF4>=1.5.8
    - pyproj
    - python-eccodes

about:
  home: https://github.com/rodri90y/gdio
  license: MIT
  license_family: MIT
  summary: gridded data io library
